FROM node:14.4.0-alpine

WORKDIR /usr/src/app

ENV PATH $PATH:/usr/src/app/node_modules/.bin

RUN apk update \
    && apk add --no-cache \
    bash \
    musl-dev

RUN npm install serve

COPY . /usr/src/app/